"""Generate the numbers.tex macro files consumed by both papers.

Reads paper_numbers.json + stats_results.json and writes
  paper/numbers.tex        (shared macro file; \\input by both papers)
No numeric value in either tex file may bypass this script -- see
verify_tex_numbers.py, which enforces it.

Macro naming: \\nb<Group><Metric>, TitleCase groups; values rounded to the
precision the tables use (3 decimals for metrics, 2 for Vendi, etc.).
"""

from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER_DIR = os.path.normpath(os.path.join(HERE, "..", ".."))

M3 = ["diversity_dino", "diversity_dreamsim", "diversity_lpips", "CLIP"]
SHORT = {"diversity_dino": "Dino", "diversity_dreamsim": "Dreamsim",
         "diversity_lpips": "Lpips", "CLIP": "Clip",
         "diversity_vendi": "Vendi", "diversity_dpp": "Dpp"}


def r3(x):
    return f"{x:.3f}"


def r2(x):
    return f"{x:.2f}"


def main():
    with open(os.path.join(HERE, "paper_numbers.json")) as fp:
        N = json.load(fp)
    stats_path = os.path.join(HERE, "stats_results.json")
    S = json.load(open(stats_path)) if os.path.exists(stats_path) else {}

    L = ["% AUTO-GENERATED by paper/full/analysis/make_numbers_tex.py -- do not edit",
         "% regenerate: python paper/full/analysis/aggregate.py && python paper/full/analysis/stats.py && python paper/full/analysis/make_numbers_tex.py"]

    def macro(name, val):
        L.append(f"\\newcommand{{\\{name}}}{{{val}}}")

    # ---- reference rows (citations, single-sourced in aggregate.py) -------- #
    ref = N["reference"]
    for row, g in [("harrington_iid", "PaperIid"), ("parmar", "Parmar"),
                   ("harrington_grad", "PaperGrad")]:
        for m in M3:
            macro(f"nb{g}{SHORT[m]}", r3(ref[row][m]))
    macro("nbPaperGradSecPerIterAHundred", ref["harrington_grad_s_per_iter_a100"])

    # ---- headline: archived merged breeding run --------------------------- #
    mg = N["geneval_merged"]
    macro("nbNumPrompts", mg["n"])
    for m in M3:
        macro(f"nbBred{SHORT[m]}", r3(mg["best"][m]))
    macro("nbBredVendi", r2(mg["best"]["diversity_vendi"]))
    macro("nbBredDpp", r3(mg["best"]["diversity_dpp"]))
    init = N["geneval_full552"]["init"]
    for m in M3:
        macro(f"nbInit{SHORT[m]}", r3(init[m]))
    macro("nbInitVendi", r2(init["diversity_vendi"]))
    macro("nbInitDpp", r3(init["diversity_dpp"]))

    # ---- design ablations table ------------------------------------------- #
    for cond, g in [("default", "AblDefault"), ("beta0", "AblBetaZero"),
                    ("beta2", "AblBetaTwo"), ("mut01", "AblMutOne"),
                    ("mut15", "AblMutFifteen"), ("noxover", "AblNoXover"),
                    ("norepair", "AblNoRepair"), ("pink", "AblPink")]:
        if cond in N.get("design_ablations", {}):
            b = N["design_ablations"][cond]["best"]
            for m in ("diversity_dino", "diversity_dreamsim", "CLIP"):
                macro(f"nb{g}{SHORT[m]}", r3(b[m]))
    if "default" in N.get("design_ablations", {}):
        di = N["design_ablations"]["default"]["init"]
        macro("nbAblInitDino", r3(di["diversity_dino"]))
        macro("nbAblInitClip", r3(di["CLIP"]))

    # ---- exploration numbers quoted in prose ------------------------------ #
    ex = N.get("explore", {})
    if "transfer" in ex:
        macro("nbTransferGainPct", f"{ex['transfer']['dino_gain_pct']:.0f}")
        macro("nbTransferIidDino", r3(ex["transfer"]["pixart_iid_dino"]))
        macro("nbTransferBredDino", r3(ex["transfer"]["pixart_bred_dino"]))
    if "setsize" in ex and "B16" in ex["setsize"]:
        macro("nbSetsizeBSixteenVendi", r2(ex["setsize"]["B16"]["best"]["diversity_vendi"]))
    if "dctnsga" in ex:
        for arm, g in [("dct_nsga", "DctNsga"), ("tensor_nsga", "TensorNsga")]:
            macro(f"nb{g}Dino", r3(ex["dctnsga"][arm]["diversity_dino"]))
            macro(f"nb{g}Clip", r3(ex["dctnsga"][arm]["CLIP"]))
    if "gp_full" in ex:
        macro("nbGpDino", r3(ex["gp_full"]["best"]["diversity_dino"]))
        macro("nbGpClip", r3(ex["gp_full"]["best"]["CLIP"]))
    if "islands" in ex:
        macro("nbIslandsCrossMin", r2(ex["islands"]["min"]))
        macro("nbIslandsCrossMax", r2(ex["islands"]["max"]))

    # ---- new experiments (present only once run) --------------------------- #
    pp = N.get("paperprep", {})
    if "e1_gradient" in pp:
        e1 = pp["e1_gradient"]
        for m in M3:
            if m in e1.get("rescored", {}):
                macro(f"nbGradSame{SHORT[m]}", r3(e1["rescored"][m]))
        if "diversity_vendi" in e1.get("rescored", {}):
            macro("nbGradSameVendi", r2(e1["rescored"]["diversity_vendi"]))
        if "diversity_dpp" in e1.get("rescored", {}):
            macro("nbGradSameDpp", r3(e1["rescored"]["diversity_dpp"]))
        macro("nbGradSameSecPerIter", f"{e1['s_per_iter_median']:.2f}")
        macro("nbGradSamePeakMemGb", f"{e1['peak_mem_alloc_gb_max']:.1f}")
        macro("nbGradSameNumPrompts", e1.get("n", ""))
    if "e2_random" in pp:
        e2 = pp["e2_random"]
        for m in M3:
            macro(f"nbRand{SHORT[m]}", r3(e2["best"][m]))
        macro("nbRandVendi", r2(e2["best"]["diversity_vendi"]))
        macro("nbRandDpp", r3(e2["best"]["diversity_dpp"]))
        if "total_renders_used" in e2:
            macro("nbRandTotalRendersM", f"{e2['total_renders_used']/1e6:.1f}")
    if "e3_cmadct" in pp:
        e3 = pp["e3_cmadct"]
        for m in M3:
            macro(f"nbCmadct{SHORT[m]}", r3(e3["best"][m]))
        macro("nbCmadctVendi", r2(e3["best"]["diversity_vendi"]))
        macro("nbCmadctDpp", r3(e3["best"]["diversity_dpp"]))

    # ---- stats macros ------------------------------------------------------ #
    def pfmt(p):
        if p < 1e-4:
            return "p{<}10^{-4}"
        return f"p{{=}}{p:.3f}" if p >= 0.001 else f"p{{=}}{p:.0e}"

    for name, g in [("cmadct_vs_bred_dino", "StatCmadctDino"),
                    ("bred_vs_grad_dino", "StatBredGradDino"),
                    ("bred_vs_rand_dino", "StatBredRandDino"),
                    ("bred_vs_grad_lpips", "StatBredGradLpips")]:
        if name in S:
            macro(f"nb{g}P", pfmt(S[name]["holm_p"]))
            macro(f"nb{g}Diff", f"{S[name]['mean_diff']:+.3f}")

    out = os.path.join(PAPER_DIR, "numbers.tex")
    with open(out, "w") as fp:
        fp.write("\n".join(L) + "\n")
    print(f"wrote {out} ({len(L) - 2} macros)")


if __name__ == "__main__":
    main()
